trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'student-flask-project'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Docker Hub Service Connection Name
  containerRegistry: 'dockerhub-connection'

  # SonarCloud Service Connection Name
  sonarCloudServiceConnection: 'student_key'

  # SonarCloud Organization Key
  sonarOrganization: 'kchandrasekhar'

  # SonarCloud Project
  sonarProjectKey: 'student-flask-project'
  sonarProjectName: 'student-flask-project'

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python 3.11'
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-cov
  displayName: 'Install Dependencies'

- task: SonarCloudPrepare@3
  displayName: 'Prepare SonarCloud Analysis'
  inputs:
    SonarCloud: '$(sonarCloudServiceConnection)'
    organization: '$(sonarOrganization)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonarProjectKey)'
    cliProjectName: '$(sonarProjectName)'

- script: |
    pytest --maxfail=1 --disable-warnings --junitxml=test-results.xml
  displayName: 'Run Unit Tests'
  continueOnError: true

- task: SonarCloudAnalyze@3
  displayName: 'Run SonarCloud Analysis'

- task: SonarCloudPublish@3
  displayName: 'Publish Quality Gate'
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: '$(containerRegistry)'
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)
      latest